### ISSUE TITLE
Step-by-step guide

### ISSUE THREAD

**Issue by tylerzika** [Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects#3]
It would be nice if there was a step-by-step guide how to get this running on a SF org in the README. I only know Salesforce development and am just starting to learn Angular. In my opinion, I shouldn't have to learn how bower and grunt work to get this running.

**Comment by kulishch** [comment]
@tylerzika while you can get this to work without Bower and Grunt, it is less efficient and requires more steps from the developer to get to work.

Bower is a package manager for front-end libraries. It helps keep track of what libraries your code is dependent on. It serves the same purpose as NuGet for .NET and Composer for PHP projects.

As you expand further into more front-end development you'll discover there are many JavaScript libraries that'll help you get the job done or help augment AngularJS to achieve your goals. Manually managing these can be tedious and error prone especially if you are collaborating with other developers. Bower makes this easier by tracking the packages and allowing the installation of them through a single command.

To bypass Bower, download AngularJS, Angular-Route, jQuery, and Bootstrap; upload them to the Static Resources in your Org; and update the references to them in the [contact_manage.page](https://github.com/Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects/blob/master/src/contact_manager.page). You can also link to them from CDN as well. Be sure to use a <script> tag at the end of the page instead of apex:includeScript. apex:includeScript loads scripts asynchronously and can cause issues with the libraries not loading.

Grunt is a task runner for front-end projects. It allows you to automate the tasks needed to get your project to run in different environments. It's like Ant only built on NodeJS instead of Java.

Again as you expand further into more front-end development you'll discover there are additional steps to prepare your front-end code for running. SASS/LESS compiling, JS unit testing, CSS minification, JS minification, and replacing URLs with environment specific ones. Grunt makes it easy to define these as different tasks and define different configurations of the to run based on the command entered. In this project I'm only using it to copy my 'src' directory to a 'dist' directory and then compressing the 'dist' directory to a ZIP file in 'bin' that can be uploaded to Salesforce as a Static Resource.

To bypass Grunt, whenever you're ready to upload to Salesforce, copy the contents of the 'src' directory to the 'dist' directory; copy the contents of the 'vendor' directory to the 'vendor' directory in 'dist' (only if you're still using Bower); compress the contents of the 'dist' directory into a ZIP file named 'ContactManagerSPA.zip' and upload it to Salesforce as a Static Resource.

Let me know if you have any other questions.
